<?php
/**
 * @file
 * IIV grid plugin for views.
 */

/**
 * Implements hook_autoload_info.
 */
function views_iiv_autoload_info() {
  return array(
    'views_plugin_style_views_iiv' => 'views_plugin_style_views_iiv.inc',
  );
}

/**
 * Implements hook_views_api()
 */
function views_iiv_views_api() {
  return array(
    'api' => '3',
    'path' => backdrop_get_path('module', 'views_iiv'),
    'template_path' => backdrop_get_path('module', 'views_iiv'),
  );
}

/**
 * Preprocess function for views-view-views-iiv.tpl.php.
 */
function template_preprocess_views_view_views_iiv(&$vars) {
  // Run preprocess function for unformatted style
  template_preprocess_views_view_unformatted($vars);
  // Get view options
  $view = $vars['view'];
  $options = $vars['options'];
}
